<?php
// This file generated by Propel 1.5.6 convert-conf target
// from XML runtime conf file /home/web/poivre.name/sites-available/tmp/devwow/WRAP/propel/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'wrap' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=wrapdev',
        'user' => 'wrapdev',
        'password' => 'fQb8avQa4axfcJ5Z',
      ),
    ),
    'default' => 'wrap',
  ),
  'generator_version' => '1.5.6',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-wrap-conf.php');
return $conf;